type(x)
-x의 데이터 타입을 반환한다.


int:정수형 데이터 타입

In [1]:
a = 1; print(type(a)) #a라는 변수에 1을 대입

<class 'int'>


float:실수형 데이터 타입

In [2]:
a = 1; a = float(a); print(type(a))

<class 'float'>


In [3]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


str:문자 데이터 타입
문자열,리스트 등의 데이터는 인덱스를 이용해 위치를 나타낸다(0부터 시작)

In [4]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


In [1]:
a='12345' #문자열

print(a[0]) #인덱스는 0부터 시작하기 때문에 값은 1
print(a[2]) #값은 3
print(a[-1]) #뒤에서부터 첫번째

1
3
5


데이터 타입: 리스트
리스트 내부에 숫자, 문자, 다른 리스트 등이 들어갈 수 있다.

In [5]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [6]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [2]:
a=[1,2,3,4] #리스트 생성

a[1]=4 #인덱스를 이용해 리스트 내부 변경 가능


print(a)

[1, 4, 3, 4]


데이터 타입:튜플

리스트와 비슷하지만 내부의 값을 변경불가능하다

In [7]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


In [4]:
a=(1,2,3,4) #튜플 생성

a[1]=4  #튜플 내부의 값은 변경불가능하기 때문에 에러 발생
print(a)

TypeError: 'tuple' object does not support item assignment

데이터 타입:딕셔너리

키:값의 형태로 값을 저장한다.

In [8]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [5]:
a={"a":1,"b":2,"c":3} #딕셔너리 생성

print(a["a"]) #a[키]의 형태로 값을 불러올수 있다.

a["d"] = 4  #이같은 형식으로 기존에 없는 키와 그 값을 저장할 수 있다.

print(a["d"])

1
4


In [9]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

넘파이 라이브러리를 이용해 행렬을 쉽게 구현가능하다.


In [13]:
import numpy as np
b = np.array(a) 
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [14]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [15]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [16]:
c*c #2x3행렬과 2x3행렬은 서로 곱할수 없기 때문에 에러 발생

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [17]:
c*c.T #뒤에 c를 전치행렬로 바꿔주고 곱셈 수행

matrix([[14, 19],
        [19, 73]])